# Generated by Django 3.2.7 on 2021-10-26 12:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('asgharzadeh', '0002_auto_20211026_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightname',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 12, 0, 39, 331544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nightname',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 26, 12, 0, 39, 331514, tzinfo=utc)),
        ),
    ]
